server:
  port: 9020
spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: update
jpa:
  properties:
    hibernate:
      current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
